# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3859ca6e0a084bb3060c9d5f0d80e0f9426af494e3fa4203c342a12ce22b68ec184675eeaaeca16583f9bb7a4140cb26da8f6a850bbe6c1db0edeeb60223ee74

test:
  secret_key_base: 5225d2fc5c21d04a1e941532228081e61ff302b03a3df1dae0f3f601aa801e2a75c4bddee6ade4131da9e9bd1a8c8045ce9dfe4ca19dba92e24be739523c7fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
